<a href="https://colab.research.google.com/github/cow-coding/School-Project/blob/master/Computer%20Science/Machine%20Learning/1.XOR_Gate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Library import

In [ ]:
import numpy as np
import torch

# Input Setting

In [ ]:
input = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Gate Make

## AND Gate

In [ ]:
def AND(x):
  result = np.empty((len(x), 1), int)

  for i in range(len(x)):
    if x[i, 0] == 1 and x[i, 1] == 1:
      result[i] = 1
    else:
      result[i] = 0

  return result

In [ ]:
AND(input)

array([[0],
       [0],
       [0],
       [1]])

## OR Gate

In [ ]:
def OR(x):
  result = np.empty((len(x), 1), int)

  for i in range(len(x)):
    if x[i, 0] == 1 or x[i, 1] == 1:
      result[i] = 1
    else:
      result[i] = 0

  return result

In [ ]:
OR(input)

array([[0],
       [1],
       [1],
       [1]])

## NAND Gate

In [ ]:
def NAND(x):
  result = np.empty((len(x), 1), int)

  for i in range(len(x)):
    if x[i, 0] == 1 and x[i, 1] == 1:
      result[i] = 0
    else:
      result[i] = 1

  return result

In [ ]:
NAND(input)

array([[1],
       [1],
       [1],
       [0]])

## XOR Gate

In [ ]:
def XOR(x):
  ret1 = NAND(x)
  ret2 = OR(x)
  
  input2 = np.concatenate([ret1, ret2], axis=1)

  y = AND(input2)

  return y

In [ ]:
XOR(input)

array([[0],
       [1],
       [1],
       [0]])